export enum NotificationStatus {
  PENDING = 'PENDING',
  SENT = 'SENT',
  DELIVERED = 'DELIVERED',
  FAILED = 'FAILED',
  READ = 'READ',
}

export enum NotificationEventType {
  // Holiday events
  HOLIDAY_ADDED = 'HOLIDAY_ADDED',
  HOLIDAY_REMOVED = 'HOLIDAY_REMOVED',
  HOLIDAY_UPDATED = 'HOLIDAY_UPDATED',

  // Staff leave events
  STAFF_LEAVE_REQUESTED = 'STAFF_LEAVE_REQUESTED',
  STAFF_LEAVE_APPROVED = 'STAFF_LEAVE_APPROVED',
  STAFF_LEAVE_REJECTED = 'STAFF_LEAVE_REJECTED',
  STAFF_LEAVE_CANCELLED = 'STAFF_LEAVE_CANCELLED',

  // Schedule events
  SCHEDULE_EVENT_CREATED = 'SCHEDULE_EVENT_CREATED',
  SCHEDULE_EVENT_UPDATED = 'SCHEDULE_EVENT_UPDATED',
  SCHEDULE_EVENT_DELETED = 'SCHEDULE_EVENT_DELETED',
  SCHEDULE_EVENT_ASSIGNED = 'SCHEDULE_EVENT_ASSIGNED',
  SCHEDULE_EVENT_UNASSIGNED = 'SCHEDULE_EVENT_UNASSIGNED',

  // Opentalk events
  OPENTALK_EVENT_CREATED = 'OPENTALK_EVENT_CREATED',
  OPENTALK_EVENT_UPDATED = 'OPENTALK_EVENT_UPDATED',
  OPENTALK_EVENT_DELETED = 'OPENTALK_EVENT_DELETED',
  OPENTALK_PARTICIPANTS_ASSIGNED = 'OPENTALK_PARTICIPANTS_ASSIGNED',
  OPENTALK_PARTICIPANTS_SWAPPED = 'OPENTALK_PARTICIPANTS_SWAPPED',

  // Cleaning events
  CLEANING_EVENT_CREATED = 'CLEANING_EVENT_CREATED',
  CLEANING_EVENT_UPDATED = 'CLEANING_EVENT_UPDATED',
  CLEANING_EVENT_DELETED = 'CLEANING_EVENT_DELETED',
  CLEANING_ASSIGNED = 'CLEANING_ASSIGNED',
  CLEANING_REASSIGNED = 'CLEANING_REASSIGNED',

  // Swap request events
  SWAP_REQUEST_CREATED = 'SWAP_REQUEST_CREATED',
  SWAP_REQUEST_APPROVED = 'SWAP_REQUEST_APPROVED',
  SWAP_REQUEST_REJECTED = 'SWAP_REQUEST_REJECTED',

  // Penalty events
  PENALTY_ASSIGNED = 'PENALTY_ASSIGNED',
  PENALTY_RESOLVED = 'PENALTY_RESOLVED',

  // Campaign events
  CAMPAIGN_STARTED = 'CAMPAIGN_STARTED',
  CAMPAIGN_ENDED = 'CAMPAIGN_ENDED',
  CAMPAIGN_UPDATED = 'CAMPAIGN_UPDATED',
}

export enum NotificationPriority {
  LOW = 'LOW',
  MEDIUM = 'MEDIUM',
  HIGH = 'HIGH',
  CRITICAL = 'CRITICAL',
}

export enum NotificationChannel {
  EMAIL = 'EMAIL',
  SMS = 'SMS',
  PUSH = 'PUSH',
  IN_APP = 'IN_APP',
  WEBHOOK = 'WEBHOOK',
}

export enum NotificationEventStatus {
  PENDING = 'PENDING',
  PROCESSING = 'PROCESSING',
  COMPLETED = 'COMPLETED',
  FAILED = 'FAILED',
  DEAD_LETTER = 'DEAD_LETTER',
}
